"""End-to-end corpus build driver.

Runs the live pull + local processing + embed, in order. Each step is independently runnable and
resumable (fetch resumes from its checkpoint; embed skips chunks already in the store).

WARNING: `fetch_wikitext` and `fetch` (and therefore `all`) hit the live MediaWiki API for the full
~36k-article corpus. The wikitext pull (`action=query`, 50 titles/call) is the fast part; rendered
HTML comes from `action=parse`, which renders ONE page per call (the Lua-decoded stat tables exist
only in the HTML), so a full HTML pull is ~19h at the configured throttle. Both are resumable. Run
deliberately.

`all` covers, in order: harvest (title list from the API), fetch_wikitext (raw wikitext for every
title via action=query), fetch (rendered HTML for the stat-page list `paths.html_titles` via
action=parse), parse (hybrid merge: HTML-parsed stat pages + wikitext-parsed prose), chunk, embed,
bm25. The stat-page title list is NOT generated by any step. See fetch_html.run for how to
provide it or fall back to all titles. Usage:

    python -m xeno_rag.pipeline all             # full build (see step list above)
    python -m xeno_rag.pipeline fetch           # just the (resumable) rendered-HTML pull
    python -m xeno_rag.pipeline fetch_wikitext  # just the (resumable) wikitext pull
    python -m xeno_rag.pipeline retry_timeouts  # re-fetch HTML pages that hit transient timeouts
"""

import argparse
import logging

from . import bm25_index, chunk, embed_index, fetch_content, fetch_html, harvest_titles, parse_html
from .config import load_config

log = logging.getLogger(__name__)

STEPS = ["harvest", "fetch_wikitext", "fetch", "parse", "chunk", "embed", "bm25"]
# `rebuild` re-PROCESSES the already-fetched corpus: its `fetch` step resumes from the HTML
# checkpoint, so after a completed pull it fetches nothing. That is deliberate (rebuild = new
# parse/chunk/embed logic over existing data, no network). To actually re-pull fresh wiki content,
# delete the checkpoints first (`paths.html_checkpoint` for HTML, `paths.checkpoint` for wikitext).
# Then: re-merge, re-chunk, a FRESH embed (drop + rebuild) because re-parsed text changes under
# existing chunk ids, then the BM25 lexical index (built from the embedded collection, so its tags
# match).
META = {"all": STEPS, "rebuild": ["fetch", "parse", "chunk", "embed_fresh", "bm25"]}


def run_step(name: str, cfg: dict):
    if name == "harvest":
        n = harvest_titles.run(cfg)
        log.info("harvest: %s titles", n)
        return n
    if name == "fetch_wikitext":
        fetch_content.run(cfg)
        log.info("fetch_wikitext: complete")
        return None
    if name == "fetch":
        fetch_html.run(cfg, log=lambda m, **k: log.info("fetch: %s", m))
        log.info("fetch: complete")
        return None
    if name == "retry_timeouts":
        # Explicit human-run step (hits the live API); NOT part of `all`/`rebuild`. Re-attempts
        # pages whose HTML fetch failed with a transient timeout, appending recovery batches.
        n = fetch_html.retry_timeouts(cfg, log=lambda m, **k: log.info("retry_timeouts: %s", m))
        log.info("retry_timeouts: %s pages re-attempted", n)
        return n
    if name == "parse":
        stats = parse_html.run_hybrid(cfg)   # HTML for stat pages, wikitext for the rest, merged
        log.info("parse: %s", stats)
        return stats
    if name == "chunk":
        n = chunk.run(cfg)
        log.info("chunk: %s chunks", n)
        return n
    if name in ("embed", "embed_fresh"):
        if name == "embed_fresh":
            embed_index.drop_collection(cfg)
            log.info("embed: dropped collection for a fresh rebuild")
        n = embed_index.run(cfg)
        log.info("embed: collection count %s", n)
        return n
    if name == "bm25":
        n = bm25_index.run(cfg)
        log.info("bm25: lexical index built over %s chunks", n)
        return n
    raise ValueError(f"unknown step: {name}")


def main(argv=None) -> None:
    parser = argparse.ArgumentParser(description="Build the Xeno RAG corpus.")
    # embed_fresh is also exposed directly (not just inside `rebuild`) so a drop+rebuild can be
    # (re)run on its own (e.g. resuming after fetch/parse/chunk already completed). retry_timeouts
    # is a standalone recovery pass (re-fetch timeout-failed HTML pages), never part of a meta step.
    parser.add_argument("step", choices=STEPS + ["embed_fresh", "retry_timeouts"] + list(META))
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print the ordered steps that WOULD run (expanding `all`/`rebuild`) and exit without "
             "touching the network, the store, or the checkpoints. Use to preview a build plan.",
    )
    args = parser.parse_args(argv)
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s"
    )
    steps = META.get(args.step, [args.step])
    if args.dry_run:
        # No config load, no side effects: just report the plan so a `rebuild`/`all` can be previewed.
        log.info("dry-run: would run steps: %s", " -> ".join(steps))
        return
    cfg = load_config()
    for step in steps:
        log.info("=== step: %s ===", step)
        run_step(step, cfg)


if __name__ == "__main__":
    main()
